CREATE DATABASE Session08
GO
USE Session08
GO
CREATE TABLE Student
(
	Id INT IDENTITY(1000,10),
	Name NVARCHAR(50) NOT NULL,
	Family NVARCHAR(50) NOT NULL,
	Email VARCHAR(80) UNIQUE NOT NULL,
	NationalCode CHAR(12) UNIQUE NOT NULL,
	CellPhone CHAR(11) UNIQUE NOT NULL,
	BirthDate DATE,
	PRIMARY KEY(Id)
)
GO
CREATE TABLE Teacher
(
	Id INT IDENTITY,
	Name NVARCHAR(50) NOT NULL,
	Family NVARCHAR(50) NOT NULL,
	Experience TINYINT,
	Email VARCHAR(100) UNIQUE NOT NULL,
	CONSTRAINT PK_Teacher_Id PRIMARY KEY(Id),
	CONSTRAINT CHK_Email CHECK(Email LIKE '%@%.%'),
	CONSTRAINT CHK_Experience CHECK (Experience > 10)
)
GO
DROP TABLE Student
GO
CREATE TABLE Student
(
	Id INT IDENTITY(1000,10),
	Name NVARCHAR(50) NOT NULL,
	Family NVARCHAR(50) NOT NULL,
	Email VARCHAR(80) UNIQUE NOT NULL,
	NationalCode CHAR(12) UNIQUE NOT NULL,
	CellPhone CHAR(11) UNIQUE NOT NULL,
	BirthDate DATE,
	PRIMARY KEY(Id),
	CHECK(CellPhone LIKE '09[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
)
GO
GO
DROP TABLE Teacher
GO
DROP TABLE Student
GO
CREATE TABLE Person
(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	Family NVARCHAR(50) NOT NULL,
	Email VARCHAR(100) NOT NULL UNIQUE,
	NationalCode CHAR(12) NOT NULL UNIQUE,
	CellPhone CHAR(11) NOT NULL UNIQUE,
	CONSTRAINT CHK_CellPhone CHECK(CellPhone LIKE '09[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	CONSTRAINT CHK_Email CHECK(Email LIKE '%@%.%'),
)
GO
CREATE TABLE Student
(
	Id INT PRIMARY KEY IDENTITY,
	PersonId INT,
	StudentCode CHAR(5),
	EntranceYear INT
)
GO
SELECT *
FROM Person p
INNER JOIN Student s
ON p.Id = s.PersonId
GO
DROP TABLE Person
GO
CREATE TABLE Student
(
	PersonId INT PRIMARY KEY FOREIGN KEY REFERENCES Person(Id),
	StudentCode CHAR(5),
	EntranceYear INT
)
GO
CREATE TABLE Teacher
(
	PersonId INT PRIMARY KEY,
	Experience TINYINT,
	FOREIGN KEY(PersonId) REFERENCES Person(Id)
)
GO
CREATE TABLE Course
(
	Id INT PRIMARY KEY IDENTITY,
	Code CHAR(12),
	Title NVARCHAR(50),
	Units TINYINT,
	TeacherId INT,
	CONSTRAINT FK_TeacherId FOREIGN KEY(TeacherId)
	REFERENCES Teacher(PersonId)
)
GO
CREATE TABLE StudentCourse
(
	StudentId INT FOREIGN KEY REFERENCES Student(PersonId),
	CourseId INT FOREIGN KEY REFERENCES Course(Id)
	CONSTRAINT PK_StudentId_CourseId
	PRIMARY KEY(StudentId,CourseId)
)
GO
DROP TABLE Student
GO
DROP TABLE StudentCourse
GO
CREATE TABLE Student
(
	PersonId INT PRIMARY KEY 
	FOREIGN KEY REFERENCES Person(Id) 
	ON UPDATE NO ACTION ON DELETE CASCADE,
	StudentCode CHAR(5),
	EntranceYear INT
)
GO
CREATE TABLE T1
(
	Id INT PRIMARY KEY,
	Name NVARCHAR(50)
)
GO
CREATE TABLE T2
(
	Id INT PRIMARY KEY,
	T1Id INT FOREIGN KEY REFERENCES T1(Id)
	ON UPDATE SET NULL ON DELETE SET DEFAULT
	DEFAULT 1
)
GO
CREATE TABLE Product
(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(50),
	CreatedDate DATETIME DEFAULT GETDATE(),
	RowGuid UNIQUEIDENTIFIER DEFAULT NEWID()
)
GO
SELECT NEWID()
GO
CREATE TABLE SalesRow
(
	Id INT IDENTITY PRIMARY KEY,
	OrderQty INT,
	UnitPrice DECIMAL(10,2),
	UnitPriceDiscount DECIMAL(3,2),
	LineTotal AS (OrderQty * UnitPrice * (1-UnitPriceDiscount))
)
GO
