CREATE DATABASE Session07
GO --Batch Separator
DROP DATABASE Session07
GO
CREATE DATABASE Session07
ON -- MDF
(
	NAME = 'Session07_Data',
	FILENAME = 'D:\DBFiles\S07.mdf',
	SIZE = 13 MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 5 MB
)
LOG ON --LDF
(
	NAME = 'Session07_Log',
	FILENAME = 'D:\DBFiles\S07.ldf',
	SIZE = 15 MB,
	MAXSIZE = 50 MB,
	FILEGROWTH = 20%
)
GO
USE Session07
GO
CREATE TABLE Student
(
	Id INT PRIMARY KEY IDENTITY(1000,10),
	Name NVARCHAR(50) NOT NULL,
	Family NVARCHAR(50) NOT NULL,
	Email VARCHAR(80) UNIQUE NOT NULL,
	NationalCode CHAR(12) UNIQUE NOT NULL,
	CellPhone CHAR(11) UNIQUE NOT NULL,
	BirthDate DATE
)
GO
