// <auto-generated />
namespace EFCodeFirstDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class categoryadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(categoryadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201903160754458_category-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
